### ISSUE TITLE
Create Lo-Fi for viewAllDepartures

### ISSUE THREAD

**Issue by groenborg** [groenborg/CharonFront#6]

**Comment by groenborg** [comment]
Create google drive, for the lo-fi models

**Comment by groenborg** [comment]
godt arbejde

**Comment by ChristopherMortensen** [comment]
tak, link til drev: https://docs.google.com/presentation/d/1hRrmiVijEFmtryfDcqOaInHBFiu8A1lOJkVEbIlX7d0/edit#slide=id.g1907436c4a_0_52
